Vagrant.configure("2") do |config|
	config.vm.define "vm1" do |vm1|
		vm1.vm.box = "mhc-cs/Ubuntu-22-04-Xfce"
		vm1.vm.network "private_network", type: "static", ip: "192.168.30.11", virtualbox__intnet: "red_controlada"
	end
	
	config.vm.define "vm2" do |vm2|
		vm2.vm.box = "techchad2022/ubuntu2204"
		vm2.vm.network "private_network", type: "dhcp", virtualbox__intnet: "red_controlada"
	end
	
	config.vm.define "vm3" do |vm3|
		vm3.vm.box = "techchad2022/ubuntu2204"
		vm3.vm.network "private_network", type: "dhcp", virtualbox__intnet: "red_controlada"
	end
end
