Vagrant.configure("2") do |config|

  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "techchad2022/ubuntu2204"
	vm1.vm.network "public_network", type:"dhcp"
	vm1.vm.provision "shell", inline: "sudo apt update"
	vm1.vm.provision "shell", inline: "sudo apt install apache2"
  end
  
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "techchad2022/ubuntu2204"
	vm2.vm.network "private_network", type:"dhcp"
	vm2.vm.provision "shell", inline: "sudo apt update"
	vm2.vm.provision "shell", inline: "sudo apt install mysql-server"
  end
  
end
