Vagrant.configure("2") do |config|
    config.vm.define "vm2" do |vm2|
        vm2.vm.box = "techchad2022/ubuntu2204"
        vm2.vm.network "private_network", type: "static", ip: "192.168.33.16", virtualboxintnet: "red_controlada"
	end

    config.vm.define "vm1" do |vm1|
        vm1.vm.box = "techchad2022/ubuntu2204"
        vm1.vm.network "private_network", type: "static", ip: "192.168.33.15", virtualboxintnet: "red_controlada"
		vm1.vm.provision "shell", path: "./scripts/ACL.sh", privileged: true, run: "always"
		vm1.vm.provision "shell", path: "./scripts/backup.sh", privileged: true, run: "always"
	end
end
